#!/usr/bin/env ansible-playbook

---
- name: Non-Privileged Tasks
  hosts: localhost
  become: False
  tasks:
      - ansible.builtin.template:
            src: templates/.bash_profile.j2
            dest: "/home/vagrant/.bash_aliases"
            backup: no
      - ansible.builtin.copy:
            src: files/.gitconfig
            dest: "/home/vagrant/.gitconfig"
            backup: no

- name: Privileged Tasks
  hosts: localhost
  become: True
  tasks:
      - ansible.builtin.lineinfile:
            dest: /etc/hosts
            line: "{{ item }}"
        loop:
          - '127.0.0.1 cmdb.student.devnetops.it'
          - '127.0.0.1 awx.student.devnetops.it'
          - '127.0.0.1 ldap.lab.local'
          - '127.0.0.1 awx.lab.local'
          - '127.0.0.1 cmdb.lab.local'
          - '127.0.0.1 git.lab.local'

- name: Tools (common)
  hosts: localhost
  become: True
  tasks:
      - ansible.builtin.package:
            name: "{{ item }}"
            state: latest
        loop:
          - tree
          - git
          - nano


- name: Clone repositories for DevNetOps
  hosts: localhost
  become: False
  vars:
    - repo_path: ~/git
    - install_repo: 'https://github.com/bsmeding/network_automation_dev_setup'
  tasks:
    - name: Create git repo
      ansible.builtin.file:
        path: "{{ repo_path  }}/student_install"
        state: directory
        mode: '0755'  

    - name: Git clone repo
      ansible.builtin.git:
        repo: '{{ install_repo }}'
        dest: "{{ repo_path  }}/student_install"     

    - name: Install required Python modules
      ansible.builtin.shell: pip3 install -r requirements.txt
      args:
        chdir: "{{ repo_path  }}/student_install"

    - name: Install required Ansible roles
      ansible.builtin.shell: ansible-galaxy role install -r roles/requirements.yml
      args:
        chdir: "{{ repo_path  }}/student_install"

    - name: Install required Ansible collections
      ansible.builtin.shell: ansible-galaxy collection install -r collections/requirements.yml
      args:
        chdir: "{{ repo_path  }}/student_install"        

    - name: Install student tools
      ansible.builtin.shell: ansible-playbook install_full.yml -i ./inventory
      args:
        chdir: "{{ repo_path  }}/student_install"             